### ISSUE TITLE
Unable to run tests on Firefox or Webkit

### ISSUE THREAD

**Issue by arctouch-thiagowerner** [saucelabs/saucectl-playwright-example#38]
It is not possible to run the tests using firefox or webkit.

Example:
````
 - name: Run all tests on Firefox
    browserName: "firefox"
    options:
      paths:
        - "features/**/*.feature"
      require:
        - "features/step_definitions/*.js"
      format:
        - "json:my-cucumber.json"
````

The process takes a long time waiting to be finished.

![Screen Shot 2022-10-26 at 17 08 01](https://user-images.githubusercontent.com/30930270/198126515-04c9ead8-b01f-41de-bb28-09b4849a35d6.png)

When we force-stop the Saucelabs job, that's the log:

````
No results reported to Sauce. $SAUCE_USERNAME and $SAUCE_ACCESS_KEY environment variables must be defined in order for reports to be uploaded to Sauce.
````

All the tests passed adequately, and this error does not reflect reality. I do have my environment variables correctly set.

This is webkit/firefox only issue.
