### ISSUE TITLE
What is the yml key to set commandtimeout 

### ISSUE THREAD

**Issue by sekharsdet** [saucelabs/saucectl-playwright-example#46]
I am running my tests on sauce labs and but whenever any command fails (for ex: the element is not found or not able to click on the element), then the script runs forever . I want my test to fail as soon by setting commandtimeout

**Comment by alexplischke** [comment]
You can define _all_ of your timeouts through your `playwright.config.ts/js` file or _some_ of the timeouts inside the saucectl suite:
```yaml
  - name: "Chromium Mac"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['.*.js']
    params:
      browserName: "chromium"
      project: "chromium"
      timeout: 10000
```
