### ISSUE TITLE
Generate and retrieve Playwright HTML report after run on SauceLabs

### ISSUE THREAD

**Issue by pascalknupper** [saucelabs/saucectl-playwright-example#67]
Right now I´m trying to integrate Playwright with SauceLabs. Test execution is working as expected, but I´m having some issues with the reports.

While running locally you can generate a nice HTML report from Playwright, but running on SauceLabs this report seems to not be generated anymore.

Is there any way to get this report after test execution on SauceLabs?

playwright.config.ts
```ts
export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI
    ? [
        ["github"],
        ["junit", { outputFile: "junit.xml" }],
        ["html", { open: "never" }],
      ]
    : [["list"], ["html", { open: "never" }]],
```

```yml
apiVersion: v1alpha
kind: playwright
sauce:
  region: eu-central-1
  concurrency: 4
  metadata:
    tags:
      - e2e
      - playwright
    build: SAUCE_RUN
playwright:
  version: package.json
  configFile: playwright.config.ts
rootDir: ./
suites:
  - name: "Chromium Win10"
    platformName: "Windows 10"
    testMatch: ['.*.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"

artifacts:
  cleanup: true
  download:
    when: always
    match:
      - playwright-report
    directory: ./playwright-report
```
